### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by Together4Business** [silktide/cookieconsent2#125]
First of all thanks for making a great tool to create easily a cookie notification bar. But I have one question, is it possible to change the color of the button?

I use the following code to implement the cookie bar on my site:

```
<!-- Begin Cookie Consent plugin by Silktide - http://silktide.com/cookieconsent -->
<script type="text/javascript">
    window.cookieconsent_options = {"message":"Onze site maakt gebruik van cookies om uw ervaring te verbeteren. Door het gebruik van onze site en het sluiten van dit vak, gaat u akkoord met het gebruik van cookies.","dismiss":"Akkoord","learnMore":"","link":null,"theme":"light-bottom"};
</script>

<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/1.0.9/cookieconsent.min.js"></script>
<!-- End Cookie Consent plugin -->
```

Further I would like to know if I need to update anything or will it work correctly all the time.

I hope you can assist me.

Kind regards,

Luuk

**Comment by Dolondro** [comment]
Hi there,

You want to change the CSS file that you're using away from light-bottom to one that you host yourself with the button colour of your choice. 

1. Save [this](https://github.com/silktide/cookieconsent2/blob/master/build/light-bottom.css) file to your website. This is minified, so you might want to copy and paste it through [this](http://www.cleancss.com/css-beautify/) website in order to get some slightly more readable code.
2. Change the code that is effecting `.cc_btn` to be the colour of your choice
3. Save it and upload it to your website
4. Update the theme in your snippet

Your new cookie consent inclusion should look something like this:

```
<!-- Begin Cookie Consent plugin by Silktide - http://silktide.com/cookieconsent -->
<script type="text/javascript">
    window.cookieconsent_options = {"message":"Onze site maakt gebruik van cookies om uw ervaring te verbeteren. Door het gebruik van onze site en het sluiten van dit vak, gaat u akkoord met het gebruik van cookies.","dismiss":"Akkoord","learnMore":"","link":null,"theme":"http://example.com/css/light-bottom-custom.css"};
</script>

<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/1.0.9/cookieconsent.min.js"></script>
<!-- End Cookie Consent plugin -->
```
