### ISSUE TITLE
Only display on first page load?

### ISSUE THREAD

**Issue by briwg** [silktide/cookieconsent2#30]
Can the banner be made to only display on the first page load? An example of this behaviour can be seen on the BBC New web site:

http://www.bbc.co.uk/news

A cookie notification banner is displayed and then if the user continues browsing it no longer appears.

**Comment by flyingeek** [comment]
Yes, it would be nice. In France, this is also what the [CNIL](http://www.cnil.fr/) does (french site in charge of the application of this law).

**Comment by briwg** [comment]
Thanks flyingeek. I think the CNIL implementation is pretty good.

**Comment by andygambles** [comment]
What you can do is add the following at the end of the consent plugin script

<pre>document.cookie="cookieconsent_dismissed=yes; path=/; domain=.yourdomain.com";</pre>

This will cancel the banner after first page load and only show again if the user starts a new browser session.

**Comment by flyingeek** [comment]
Thanks andygambles

**Comment by Wanabo** [comment]
This works, document.cookie="cookieconsent_dismissed=yes; path=/; domain=.yourdomain.com";
But I want to replace domain=.yourdomain.com with something universal, because I have multiple sites I want to implement this and would not edit every file seperately. 
I tried:
document.cookie="cookieconsent_dismissed=yes; path=/; domain=."+this.options.domain+"";
document.cookie="cookieconsent_dismissed=yes; path=/; domain=.null";
and other things, but my js knowledge is allmost null.

How to make this universal?

**Comment by andygambles** [comment]
You can only set the cookie on the current domain.

On Sunday, August 2, 2015, Wanabo <notifications@github.com> wrote:

> This works, document.cookie="cookieconsent_dismissed=yes; path=/; domain=.
> yourdomain.com";
> But I want to replace domain=.yourdomain.com with something universal,
> because I have multiple sites I want to implement this and would not edit
> every file seperately.
> I tried:
> document.cookie="cookieconsent_dismissed=yes; path=/;
> domain=."+this.options.domain+"";
> document.cookie="cookieconsent_dismissed=yes; path=/; domain=.null";
> and other things, but my js knowledge is allmost null.
>
> How to make this universal?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/silktide/cookieconsent2/issues/30#issuecomment-127045905>
> .
>


-- 

----

Andy Gambles

https://www.andygambles.com
https://twitter.com/andygambles

Tel: 01723 361931
Mob: 07958 944629

**Comment by Wanabo** [comment]
Found a universal way. Let the js experts decide if it is correct. Anyway it works.
Add at the end of cookieconsent.js
set_cookie(DISMISSED_COOKIE, 'yes', this.options.expiryDays, this.options.domain, this.options.path);

**Comment by Wanabo** [comment]
Yes that is my intention to set the cookie on the current domain. But can't the current domain not retrieved automatically for example with document.location or window.location.host, and set accordingly?

**Comment by briwg** [comment]
The behaviour of this:

document.cookie="cookieconsent_dismissed=yes; path=/; domain=.yourdomain.com";

Seems to be inconsistent?

In Firefox and Chrome:
1) Open the browser and the message displays only on the first page load
2) Close the browser and open a new session
3) Message NOT displayed

In IE and Safari
1) Open the browser and the message displays only on the first page load
2) Close the browser and open a new session
3) Message IS displayed

In other it only seems to work in IE for the current session whereas in Chrome and Firefox it is not session dependent. 

I would like the default behaviour to be like it is in Chrome and Firefox.

Any ideas?

**Comment by bshilpaa** [comment]
Hello,

I am not a developer and we have added the javascript directly into our CMS as below

<script type="text/javascript">
    window.cookieconsent_options = {"message":"This website uses cookies to ensure you get the best experience on our website","dismiss":"Got it!","learnMore":"More info","link":null,"theme":"dark-bottom"};

</script>

<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/1.0.9/cookieconsent.min.js">
</script>


Can you let me know where to add the code "document.cookie="cookieconsent_dismissed=yes; path=/; domain=.yourdomain.com; so that I can avoid showing the cookie consent on every page?

Also, the css is not loading properly as the cookie consent text is not visible and is appearing in black.
Can you please help me?
![cookieconsent text appearing in black](https://cloud.githubusercontent.com/assets/15670290/10967506/19789182-83b3-11e5-959c-1f2ecc6a7554.jpg)
